version: '3.4'
services:
  app:
    build:
      context: .
      target: build
    environment:
      - TS_NODE_FILES=true
      - NODE_ENV=development
      - NODE_CONFIG_ENV=development
      - |
        NODE_CONFIG={
          "kafka": {
            "global": {
              "kafkaHost": "kafka:9092"
            }
          },
          "sequelize": { "host": "postgres" },
          "orm": { "host": "postgres" },
          "redis": { "host": "redis" }
        }
    networks:
      - default
    ports:
      - '4000:4000'
    command: 'yarn watch:cmd node --inspect=9000 -r ts-node/register src/index.ts'
    volumes:
      - '.:/code'
      - /code/node_modules
networks:
  default: {}
