apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pdf-filler-deployment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pdf-filler
    spec:
      containers:
      - name: pdf-filler
        image: gcr.io/co-gcp/pdf-filler
        env:
        - name: NODE_ENV
          value: ${STAGE}
        - name: NODE_CONFIG_ENV
          value: ${STAGE}
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        livenessProbe:
          httpGet:
            path: /pdf-filler/healthcheck
            port: 4000
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /pdf-filler/healthcheck
            port: 4000
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 1
